[workspace]
members = [
    "crates/rez-next-common",
    "crates/rez-next-version",
    "crates/rez-next-package",
    "crates/rez-next-solver",
    "crates/rez-next-repository",
    "crates/rez-next-context",
    "crates/rez-next-build",
    "crates/rez-next-cache",
]
exclude = [
    "examples/rez-lsp-integration",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["LongHao <hal.long@outlook.com>"]
license = "Apache-2.0"
repository = "https://github.com/loonghao/rez-next"
keywords = ["rez", "package-manager", "dependencies", "version-management"]
categories = ["development-tools"]

[workspace.dependencies]
# External dependencies
# Temporarily disabled Python bindings
# pyo3 = { version = "0.25", features = ["extension-module", "abi3-py38"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
rayon = "1.10"
lru = "0.14.0"
tokio = { version = "1.45", features = ["full"] }
regex = "1.11"
thiserror = "2.0"
rand = "0.9"
clap = { version = "4.5", features = ["derive", "env"] }

# Dev dependencies
criterion = { version = "0.7", features = ["html_reports"] }
proptest = "1.7"
rstest = "0.25"
tempfile = "3.20"
assert_matches = "1.5"
pretty_assertions = "1.4"
serial_test = "3.2"

[package]
name = "rez-next"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Next-generation Rez package manager written in Rust"
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "rez_core"
crate-type = ["rlib"]

[features]
default = []
# Python bindings feature (currently disabled but defined to avoid warnings)
python-bindings = [
    "rez-next-common/python-bindings",
    "rez-next-version/python-bindings",
    "rez-next-package/python-bindings",
    "rez-next-context/python-bindings",
    "rez-next-solver/python-bindings",
    # "pyo3"  # Temporarily disabled
]

[[bin]]
name = "rez-next"
path = "src/bin/rez-next.rs"

[dependencies]
# Workspace crates
rez-next-common = { version = "0.1.0", path = "crates/rez-next-common", default-features = false }
rez-next-version = { version = "0.1.0", path = "crates/rez-next-version", default-features = false }
rez-next-package = { version = "0.1.0", path = "crates/rez-next-package", default-features = false }
rez-next-solver = { version = "0.1.0", path = "crates/rez-next-solver", default-features = false }
rez-next-repository = { version = "0.1.0", path = "crates/rez-next-repository", default-features = false }
rez-next-context = { version = "0.1.0", path = "crates/rez-next-context", default-features = false }
# rez-core-rex = { path = "crates/rez-core-rex" }  # Temporarily disabled due to compilation errors
rez-next-build = { version = "0.1.0", path = "crates/rez-next-build" }
rez-next-cache = { version = "0.1.0", path = "crates/rez-next-cache" }
# rez-core-python = { path = "crates/rez-core-python" }  # Temporarily disabled due to DLL issues

# Python bindings - temporarily disabled
# pyo3 = { workspace = true, optional = true }

# CLI dependencies
clap.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
regex.workspace = true
tempfile.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
rstest.workspace = true
tempfile.workspace = true
assert_matches.workspace = true
pretty_assertions.workspace = true
serial_test.workspace = true
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true



[[bench]]
name = "version_benchmark"
harness = false

[[bench]]
name = "comprehensive_benchmark_suite"
harness = false

[[bench]]
name = "package_benchmark"
harness = false

[[bench]]
name = "simple_package_benchmark"
harness = false

# Removed redundant benchmarks

[[bench]]
name = "solver_benchmark"
harness = false

[[bench]]
name = "solver_benchmark_main"
harness = false

# Simplified solver benchmarks

# Temporarily disabled context benchmarks due to API changes
# [[bench]]
# name = "context_benchmark"
# harness = false

# [[bench]]
# name = "context_benchmark_main"
# harness = false

# Temporarily disabled benchmarks due to API changes
# [[bench]]
# name = "simple_context_benchmark"
# harness = false

# Rex System Benchmarks - Temporarily disabled
# [[bench]]
# name = "rex_benchmark_main"
# harness = false

# [[bench]]
# name = "simple_rex_benchmark"
# harness = false

# Build and Cache System Benchmarks - Temporarily disabled
# [[bench]]
# name = "build_cache_benchmark_main"
# harness = false

# [[bench]]
# name = "simple_build_cache_benchmark"
# harness = false

# Performance Validation Benchmarks
[[bench]]
name = "performance_validation_benchmark"
harness = false

[[bench]]
name = "performance_validation_main"
harness = false

# [build-dependencies]
# pyo3-build-config = "0.25"  # Only needed for Python bindings

# flamegraph = ["pprof"]

# Linting configuration
[lints.rust]
# Allow unused imports for Python bindings that may not be used in all builds
unused_imports = "allow"
# Allow dead code for experimental features
dead_code = "allow"

[lints.clippy]
# Allow some clippy lints that are too strict for development
too_many_arguments = "allow"
module_inception = "allow"
# Focus on critical issues only
complexity = { level = "warn", priority = -1 }
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
perf = { level = "warn", priority = -1 }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
lto = false
