use rez_core::version::{Version, VersionRange};
use rez_next_package::{Package, PackageRequirement, Requirement};
use rez_next_rex::{generate_shell_script, RexEnvironment, RexExecutor, ShellType};
use rez_next_suites::{Suite, ToolConflictMode};

// ─── Context serialization compatibility tests ──────────────────────────────

/// rez contexts can be saved and loaded from .rxt files
#[test]
fn test_context_json_serialize_roundtrip() {
    use rez_next_context::{ContextFormat, ContextSerializer, ContextStatus, ResolvedContext};
    use rez_next_package::{Package, PackageRequirement};
    use rez_next_version::Version;

    let reqs = vec![
        PackageRequirement::parse("python-3.11").unwrap(),
        PackageRequirement::parse("maya-2024").unwrap(),
    ];
    let mut ctx = ResolvedContext::from_requirements(reqs);
    ctx.status = ContextStatus::Resolved;
    ctx.name = Some("compat_test_ctx".to_string());
    let mut py_pkg = Package::new("python".to_string());
    py_pkg.version = Some(Version::parse("3.11.0").unwrap());
    ctx.resolved_packages.push(py_pkg);
    ctx.environment_vars
        .insert("REZ_USED".to_string(), "1".to_string());

    let bytes = ContextSerializer::serialize(&ctx, ContextFormat::Json).unwrap();
    let restored = ContextSerializer::deserialize(&bytes, ContextFormat::Json).unwrap();

    assert_eq!(restored.id, ctx.id);
    assert_eq!(restored.name, ctx.name);
    assert_eq!(restored.resolved_packages.len(), 1);
    assert_eq!(
        restored.environment_vars.get("REZ_USED"),
        Some(&"1".to_string())
    );
}

/// Context .rxt file save/load via async API
#[test]
fn test_context_rxt_file_roundtrip() {
    use rez_next_context::{ContextFileUtils, ContextFormat, ContextSerializer, ResolvedContext};
    use rez_next_package::PackageRequirement;

    let rt = tokio::runtime::Runtime::new().unwrap();

    let dir = tempfile::tempdir().unwrap();
    let rxt_path = dir.path().join("ctx_test.rxt");

    let reqs = vec![PackageRequirement::parse("houdini-20").unwrap()];
    let mut ctx = ResolvedContext::from_requirements(reqs);
    ctx.name = Some("houdini_ctx".to_string());

    // Save
    rt.block_on(ContextSerializer::save_to_file(
        &ctx,
        &rxt_path,
        ContextFormat::Json,
    ))
    .unwrap();
    assert!(rxt_path.exists());

    // Load
    let loaded = rt
        .block_on(ContextSerializer::load_from_file(&rxt_path))
        .unwrap();
    assert_eq!(loaded.id, ctx.id);
    assert_eq!(loaded.name, Some("houdini_ctx".to_string()));

    // Verify it's detected as a context file
    assert!(ContextFileUtils::is_context_file(&rxt_path));
}

/// Context validation
#[test]
fn test_context_validation_valid() {
    use rez_next_context::{ContextSerializer, ContextStatus, ResolvedContext};
    use rez_next_package::{Package, PackageRequirement};
    use rez_next_version::Version;

    let rt = tokio::runtime::Runtime::new().unwrap();
    let dir = tempfile::tempdir().unwrap();
    let rxt_path = dir.path().join("valid.rxt");

    let reqs = vec![PackageRequirement::parse("python-3.9").unwrap()];
    let mut ctx = ResolvedContext::from_requirements(reqs);
    ctx.status = ContextStatus::Resolved;

    // Add resolved package so validation sees requirements satisfied
    let mut py = Package::new("python".to_string());
    py.version = Some(Version::parse("3.9").unwrap());
    ctx.resolved_packages.push(py);

    rt.block_on(ContextSerializer::save_to_file(
        &ctx,
        &rxt_path,
        rez_next_context::ContextFormat::Json,
    ))
    .unwrap();

    let validation = rt
        .block_on(ContextSerializer::validate_file(&rxt_path))
        .unwrap();
    assert!(
        validation.is_valid,
        "Valid context file should pass validation"
    );
}

/// Context export to env file format
#[test]
fn test_context_export_env_file() {
    use rez_next_context::{ContextSerializer, ContextStatus, ExportFormat, ResolvedContext};
    use rez_next_package::PackageRequirement;

    let reqs = vec![PackageRequirement::parse("maya-2024").unwrap()];
    let mut ctx = ResolvedContext::from_requirements(reqs);
    ctx.status = ContextStatus::Resolved;
    ctx.environment_vars
        .insert("MAYA_ROOT".to_string(), "/opt/maya/2024".to_string());

    let env_str = ContextSerializer::export_context(&ctx, ExportFormat::Env).unwrap();
    assert!(env_str.contains("MAYA_ROOT=/opt/maya/2024"));
    assert!(env_str.contains("# Generated by rez-core") || env_str.contains("# Context:"));
}

