//! Tests for shell script generators — extracted from shell.rs (Cycle 183)

use super::*;
use crate::RexEnvironment;

fn make_env() -> RexEnvironment {
    let mut env = RexEnvironment::new();
    env.vars
        .insert("MY_ROOT".to_string(), "/opt/pkg/1.0".to_string());
    env.vars
        .insert("PATH".to_string(), "/opt/pkg/1.0/bin:/usr/bin".to_string());
    env.aliases
        .insert("mypkg".to_string(), "/opt/pkg/1.0/bin/mypkg".to_string());
    env
}

#[test]
fn test_bash_script_contains_export() {
    let env = make_env();
    let script = generate_shell_script(&env, &ShellType::Bash);
    assert!(script.contains("export MY_ROOT="));
    assert!(script.contains("export PATH="));
    assert!(script.contains("alias mypkg="));
}

#[test]
fn test_fish_script_uses_set_gx() {
    let env = make_env();
    let script = generate_shell_script(&env, &ShellType::Fish);
    assert!(script.contains("set -gx MY_ROOT"));
    assert!(script.contains("alias mypkg"));
}

#[test]
fn test_powershell_script_uses_env_var() {
    let env = make_env();
    let script = generate_shell_script(&env, &ShellType::PowerShell);
    assert!(script.contains("$env:MY_ROOT"));
    assert!(script.contains("Set-Alias"));
}

#[test]
fn test_cmd_script_uses_set() {
    let env = make_env();
    let script = generate_shell_script(&env, &ShellType::Cmd);
    assert!(script.contains("SET MY_ROOT="));
    assert!(script.contains("DOSKEY mypkg="));
}

#[test]
fn test_shell_type_from_str() {
    assert_eq!(ShellType::parse("bash"), Some(ShellType::Bash));
    assert_eq!(ShellType::parse("zsh"), Some(ShellType::Zsh));
    assert_eq!(ShellType::parse("powershell"), Some(ShellType::PowerShell));
    assert_eq!(ShellType::parse("pwsh"), Some(ShellType::PowerShell));
    assert_eq!(ShellType::parse("fish"), Some(ShellType::Fish));
    assert_eq!(ShellType::parse("cmd"), Some(ShellType::Cmd));
    assert_eq!(ShellType::parse("unknown"), None);
}

#[test]
fn test_empty_env_generates_header_only() {
    let env = RexEnvironment::new();
    let script = generate_shell_script(&env, &ShellType::Bash);
    assert!(script.contains("Generated by rez-next rex"));
    // No export lines for empty env
    assert!(!script.contains("export "));
}

#[test]
fn test_bash_escapes_special_chars() {
    let mut env = RexEnvironment::new();
    env.vars
        .insert("MY_VAR".to_string(), "value with \"quotes\"".to_string());
    let script = generate_shell_script(&env, &ShellType::Bash);
    assert!(script.contains("\\\"quotes\\\""));
}

#[test]
fn test_powershell_escapes_single_quotes() {
    let mut env = RexEnvironment::new();
    env.vars
        .insert("MY_VAR".to_string(), "it's a test".to_string());
    let script = generate_shell_script(&env, &ShellType::PowerShell);
    assert!(script.contains("it''s a test"));
}

#[test]
fn test_startup_commands_included() {
    let mut env = RexEnvironment::new();
    env.startup_commands.push("echo 'activated'".to_string());
    let script = generate_shell_script(&env, &ShellType::Bash);
    assert!(script.contains("echo 'activated'"));
}

// ── Phase 90: Detailed shell script output comparison ────────────────────

fn make_full_env() -> RexEnvironment {
    let mut env = RexEnvironment::new();
    env.vars
        .insert("MYAPP_ROOT".to_string(), "/opt/myapp/1.2.3".to_string());
    env.vars
        .insert("MYAPP_VERSION".to_string(), "1.2.3".to_string());
    env.vars.insert(
        "PATH".to_string(),
        "/opt/myapp/1.2.3/bin:/usr/bin".to_string(),
    );
    env.aliases.insert(
        "myapp".to_string(),
        "/opt/myapp/1.2.3/bin/myapp".to_string(),
    );
    env.aliases.insert(
        "myrend".to_string(),
        "/opt/myapp/1.2.3/bin/myrend --headless".to_string(),
    );
    env.startup_commands
        .push("echo 'myapp 1.2.3 activated'".to_string());
    env
}

#[test]
fn test_bash_full_output() {
    let env = make_full_env();
    let script = generate_shell_script(&env, &ShellType::Bash);
    assert!(
        script.contains("# Generated by rez-next rex"),
        "Missing header"
    );
    assert!(
        script.contains("export MYAPP_ROOT=\"/opt/myapp/1.2.3\""),
        "Missing MYAPP_ROOT export"
    );
    assert!(
        script.contains("export MYAPP_VERSION=\"1.2.3\""),
        "Missing MYAPP_VERSION export"
    );
    assert!(script.contains("alias myapp="), "Missing myapp alias");
    assert!(script.contains("alias myrend="), "Missing myrend alias");
    assert!(
        script.contains("echo 'myapp 1.2.3 activated'"),
        "Missing startup command"
    );
    let export_pos = script.find("export MYAPP").unwrap();
    let alias_pos = script.find("alias myapp").unwrap();
    assert!(
        export_pos < alias_pos,
        "exports should appear before aliases"
    );
}

#[test]
fn test_zsh_same_as_bash() {
    let env = make_full_env();
    let bash_script = generate_shell_script(&env, &ShellType::Bash);
    let zsh_script = generate_shell_script(&env, &ShellType::Zsh);
    assert_eq!(
        bash_script, zsh_script,
        "Zsh and Bash should produce identical scripts"
    );
}

#[test]
fn test_fish_full_output() {
    let env = make_full_env();
    let script = generate_shell_script(&env, &ShellType::Fish);
    assert!(
        script.contains("set -gx MYAPP_ROOT"),
        "Missing MYAPP_ROOT set -gx"
    );
    assert!(
        script.contains("set -gx MYAPP_VERSION"),
        "Missing MYAPP_VERSION set -gx"
    );
    assert!(
        script.contains("alias myapp"),
        "Missing myapp alias in fish"
    );
    assert!(
        script.contains("echo 'myapp 1.2.3 activated'"),
        "Missing startup cmd"
    );
    assert!(
        !script.contains("export MYAPP_ROOT"),
        "Fish should not use export"
    );
}

#[test]
fn test_powershell_full_output() {
    let env = make_full_env();
    let script = generate_shell_script(&env, &ShellType::PowerShell);
    assert!(
        script.contains("$env:MYAPP_ROOT = '/opt/myapp/1.2.3'"),
        "Missing $env:MYAPP_ROOT"
    );
    assert!(
        script.contains("$env:MYAPP_VERSION = '1.2.3'"),
        "Missing $env:MYAPP_VERSION"
    );
    assert!(
        script.contains("Set-Alias -Name myapp"),
        "Missing Set-Alias myapp"
    );
    assert!(
        script.contains("echo 'myapp 1.2.3 activated'"),
        "Missing startup cmd"
    );
    assert!(
        !script.contains("export "),
        "PowerShell should not use export keyword"
    );
}

#[test]
fn test_cmd_full_output() {
    let env = make_full_env();
    let script = generate_shell_script(&env, &ShellType::Cmd);
    assert!(script.contains("@echo off"), "Missing @echo off");
    assert!(
        script.contains("SET MYAPP_ROOT=/opt/myapp/1.2.3"),
        "Missing SET MYAPP_ROOT"
    );
    assert!(
        script.contains("SET MYAPP_VERSION=1.2.3"),
        "Missing SET MYAPP_VERSION"
    );
    assert!(script.contains("DOSKEY myapp="), "Missing DOSKEY myapp");
    assert!(
        script.contains("\r\n"),
        "CMD script should use CRLF line endings"
    );
}

#[test]
fn test_bash_alias_with_spaces_escaped() {
    let mut env = RexEnvironment::new();
    env.aliases
        .insert("it".to_string(), "it's a tool".to_string());
    let script = generate_shell_script(&env, &ShellType::Bash);
    assert!(
        script.contains("it'\\''s"),
        "Single quote in alias should be escaped: {}",
        script
    );
}

#[test]
fn test_empty_env_no_spurious_sections() {
    let env = RexEnvironment::new();
    for shell in [ShellType::Bash, ShellType::Fish, ShellType::PowerShell] {
        let script = generate_shell_script(&env, &shell);
        assert!(
            !script.contains("export "),
            "Empty env: no export in {:?}",
            shell
        );
        assert!(
            !script.contains("alias "),
            "Empty env: no alias in {:?}",
            shell
        );
    }
    let cmd = generate_shell_script(&env, &ShellType::Cmd);
    assert!(!cmd.contains("SET "), "Empty env CMD: no SET");
    assert!(!cmd.contains("DOSKEY"), "Empty env CMD: no DOSKEY");
}

#[test]
fn test_multiple_startup_commands_order() {
    let mut env = RexEnvironment::new();
    env.startup_commands.push("cmd_first".to_string());
    env.startup_commands.push("cmd_second".to_string());
    env.startup_commands.push("cmd_third".to_string());
    let script = generate_shell_script(&env, &ShellType::Bash);
    let pos1 = script.find("cmd_first").unwrap();
    let pos2 = script.find("cmd_second").unwrap();
    let pos3 = script.find("cmd_third").unwrap();
    assert!(
        pos1 < pos2 && pos2 < pos3,
        "Startup commands should appear in order"
    );
}

#[test]
fn test_shell_from_str_all_variants() {
    let cases = [
        ("bash", ShellType::Bash),
        ("zsh", ShellType::Zsh),
        ("fish", ShellType::Fish),
        ("cmd", ShellType::Cmd),
        ("powershell", ShellType::PowerShell),
        ("pwsh", ShellType::PowerShell),
    ];
    for (s, expected) in &cases {
        let got = ShellType::parse(s);
        assert_eq!(got, Some(expected.clone()), "parse('{}') failed", s);
    }
    assert_eq!(
        ShellType::parse("BASH"),
        Some(ShellType::Bash),
        "Case-insensitive"
    );
    assert!(ShellType::parse("notashell").is_none());
}

// ── Phase 97: source() statement shell script output ─────────────────────

#[test]
fn test_bash_source_script() {
    let mut env = RexEnvironment::new();
    env.sourced_scripts.push("/opt/myapp/setup.sh".to_string());
    let script = generate_shell_script(&env, &ShellType::Bash);
    assert!(
        script.contains("# Sourced scripts"),
        "Missing sourced scripts section"
    );
    assert!(
        script.contains("source \"/opt/myapp/setup.sh\""),
        "Missing bash source line"
    );
}

#[test]
fn test_fish_source_script() {
    let mut env = RexEnvironment::new();
    env.sourced_scripts
        .push("/opt/myapp/setup.fish".to_string());
    let script = generate_shell_script(&env, &ShellType::Fish);
    assert!(
        script.contains("source \"/opt/myapp/setup.fish\""),
        "Missing fish source line"
    );
}

#[test]
fn test_cmd_call_script() {
    let mut env = RexEnvironment::new();
    env.sourced_scripts
        .push("C:\\opt\\myapp\\setup.bat".to_string());
    let script = generate_shell_script(&env, &ShellType::Cmd);
    assert!(
        script.contains("CALL \"C:\\opt\\myapp\\setup.bat\""),
        "Missing CMD CALL line"
    );
    assert!(
        script.contains("REM Sourced scripts"),
        "Missing CMD sourced section"
    );
}

#[test]
fn test_powershell_dot_source() {
    let mut env = RexEnvironment::new();
    env.sourced_scripts
        .push("C:\\opt\\myapp\\setup.ps1".to_string());
    let script = generate_shell_script(&env, &ShellType::PowerShell);
    assert!(
        script.contains(". 'C:\\opt\\myapp\\setup.ps1'"),
        "Missing PS dot-source: {}",
        script
    );
    assert!(
        script.contains("# Sourced scripts"),
        "Missing PS sourced section"
    );
}

#[test]
fn test_source_expands_with_executor() {
    use crate::executor::RexExecutor;
    let mut exec = RexExecutor::new();
    let env = exec
        .execute_commands(
            r#"source("{root}/etc/setup.sh")"#,
            "mypkg",
            Some("/opt/mypkg/1.0"),
            None,
        )
        .unwrap();
    assert_eq!(env.sourced_scripts.len(), 1);
    assert_eq!(env.sourced_scripts[0], "/opt/mypkg/1.0/etc/setup.sh");
}

#[test]
fn test_multiple_sources_order() {
    let mut env = RexEnvironment::new();
    env.sourced_scripts.push("/first.sh".to_string());
    env.sourced_scripts.push("/second.sh".to_string());
    let script = generate_shell_script(&env, &ShellType::Bash);
    let pos1 = script.find("/first.sh").unwrap();
    let pos2 = script.find("/second.sh").unwrap();
    assert!(pos1 < pos2, "Sources should appear in order");
}
