//! Shell script generators for Rex environments
//!
//! Converts a RexEnvironment into shell-specific activation scripts.

use crate::RexEnvironment;

/// Supported shell types
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ShellType {
    Bash,
    Zsh,
    Fish,
    Cmd,
    PowerShell,
}

impl std::str::FromStr for ShellType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "bash" => Ok(Self::Bash),
            "zsh" => Ok(Self::Zsh),
            "fish" => Ok(Self::Fish),
            "cmd" => Ok(Self::Cmd),
            "powershell" | "pwsh" => Ok(Self::PowerShell),
            _ => Err(format!("unknown shell type: {s}")),
        }
    }
}

impl ShellType {
    /// Parse from string, returning None for unknown shell types
    pub fn parse(s: &str) -> Option<Self> {
        s.parse().ok()
    }
}

/// Generate a shell activation script from a RexEnvironment
pub fn generate_shell_script(env: &RexEnvironment, shell: &ShellType) -> String {
    match shell {
        ShellType::Bash | ShellType::Zsh => generate_bash_script(env),
        ShellType::Fish => generate_fish_script(env),
        ShellType::Cmd => generate_cmd_script(env),
        ShellType::PowerShell => generate_powershell_script(env),
    }
}

/// Generate bash/zsh activation script
fn generate_bash_script(env: &RexEnvironment) -> String {
    let mut lines = Vec::new();
    lines.push("# Generated by rez-next rex".to_string());
    lines.push(String::new());

    // Environment variables
    let mut vars: Vec<_> = env.vars.iter().collect();
    vars.sort_by_key(|(k, _)| k.as_str());
    for (key, value) in &vars {
        // Escape double quotes in value
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        lines.push(format!("export {}=\"{}\"", key, escaped));
    }

    if !env.vars.is_empty() && !env.aliases.is_empty() {
        lines.push(String::new());
    }

    // Aliases
    let mut aliases: Vec<_> = env.aliases.iter().collect();
    aliases.sort_by_key(|(k, _)| k.as_str());
    for (name, cmd) in &aliases {
        let escaped = cmd.replace('\'', "'\\''");
        lines.push(format!("alias {}='{}'", name, escaped));
    }

    // Startup commands
    if !env.startup_commands.is_empty() {
        lines.push(String::new());
        lines.push("# Startup commands".to_string());
        for cmd in &env.startup_commands {
            lines.push(cmd.clone());
        }
    }

    // Sourced scripts
    if !env.sourced_scripts.is_empty() {
        lines.push(String::new());
        lines.push("# Sourced scripts".to_string());
        for script in &env.sourced_scripts {
            let escaped = script.replace('"', "\\\"");
            lines.push(format!("source \"{}\"", escaped));
        }
    }

    // Info messages (as comments in generated script)
    if !env.info_messages.is_empty() {
        lines.push(String::new());
        lines.push("# Info messages".to_string());
        for msg in &env.info_messages {
            let escaped = msg.replace('\'', "'\\''");
            lines.push(format!("# [info] {}", escaped));
        }
    }

    lines.join("\n")
}

/// Generate fish shell activation script
fn generate_fish_script(env: &RexEnvironment) -> String {
    let mut lines = Vec::new();
    lines.push("# Generated by rez-next rex".to_string());
    lines.push(String::new());

    let mut vars: Vec<_> = env.vars.iter().collect();
    vars.sort_by_key(|(k, _)| k.as_str());
    for (key, value) in &vars {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        lines.push(format!("set -gx {} \"{}\"", key, escaped));
    }

    if !env.vars.is_empty() && !env.aliases.is_empty() {
        lines.push(String::new());
    }

    let mut aliases: Vec<_> = env.aliases.iter().collect();
    aliases.sort_by_key(|(k, _)| k.as_str());
    for (name, cmd) in &aliases {
        lines.push(format!("alias {} \"{}\"", name, cmd));
    }

    if !env.startup_commands.is_empty() {
        lines.push(String::new());
        for cmd in &env.startup_commands {
            lines.push(cmd.clone());
        }
    }

    // Sourced scripts (fish uses 'source' command)
    if !env.sourced_scripts.is_empty() {
        lines.push(String::new());
        for script in &env.sourced_scripts {
            let escaped = script.replace('"', "\\\"");
            lines.push(format!("source \"{}\"", escaped));
        }
    }

    lines.join("\n")
}

/// Generate Windows CMD activation script
fn generate_cmd_script(env: &RexEnvironment) -> String {
    let mut lines = Vec::new();
    lines.push("@echo off".to_string());
    lines.push("REM Generated by rez-next rex".to_string());
    lines.push(String::new());

    let mut vars: Vec<_> = env.vars.iter().collect();
    vars.sort_by_key(|(k, _)| k.as_str());
    for (key, value) in &vars {
        lines.push(format!("SET {}={}", key, value));
    }

    if !env.aliases.is_empty() {
        lines.push(String::new());
        lines.push("REM Aliases (doskey macros)".to_string());
        let mut aliases: Vec<_> = env.aliases.iter().collect();
        aliases.sort_by_key(|(k, _)| k.as_str());
        for (name, cmd) in &aliases {
            lines.push(format!("DOSKEY {}={}", name, cmd));
        }
    }

    if !env.startup_commands.is_empty() {
        lines.push(String::new());
        for cmd in &env.startup_commands {
            lines.push(cmd.clone());
        }
    }

    if !env.sourced_scripts.is_empty() {
        lines.push(String::new());
        lines.push("REM Sourced scripts".to_string());
        for script in &env.sourced_scripts {
            lines.push(format!("CALL \"{}\"", script));
        }
    }

    lines.join("\r\n")
}

/// Generate PowerShell activation script
fn generate_powershell_script(env: &RexEnvironment) -> String {
    let mut lines = Vec::new();
    lines.push("# Generated by rez-next rex".to_string());
    lines.push(String::new());

    let mut vars: Vec<_> = env.vars.iter().collect();
    vars.sort_by_key(|(k, _)| k.as_str());
    for (key, value) in &vars {
        let escaped = value.replace('\'', "''");
        lines.push(format!("$env:{} = '{}'", key, escaped));
    }

    if !env.vars.is_empty() && !env.aliases.is_empty() {
        lines.push(String::new());
    }

    let mut aliases: Vec<_> = env.aliases.iter().collect();
    aliases.sort_by_key(|(k, _)| k.as_str());
    for (name, cmd) in &aliases {
        lines.push(format!("Set-Alias -Name {} -Value \"{}\"", name, cmd));
    }

    if !env.startup_commands.is_empty() {
        lines.push(String::new());
        lines.push("# Startup commands".to_string());
        for cmd in &env.startup_commands {
            lines.push(cmd.clone());
        }
    }

    if !env.sourced_scripts.is_empty() {
        lines.push(String::new());
        lines.push("# Sourced scripts".to_string());
        for script in &env.sourced_scripts {
            let escaped = script.replace('\'', "''");
            lines.push(format!(". '{}'", escaped));
        }
    }

    lines.join("\n")
}

#[cfg(test)]
#[path = "shell_tests.rs"]
mod tests;
